// This file is auto-generated by scripts/generate_stage_scene_ops.py
// Do not edit manually - run 'npm run generate-stage-scene-ops' to update

export const GeneratedStageSceneOperationSchemas = [] as const;

export const GeneratedStageSceneRequestOperationSchemas = GeneratedStageSceneOperationSchemas;

export const generatedCameraManifestFields = (operation: { focus_distance?: number }) => ({
	...(operation.focus_distance === undefined ? {} : { focusDistance: operation.focus_distance }),
});

export const generatedLightManifestFields = (operation: { cutoff_distance?: number }) => ({
	...(operation.cutoff_distance === undefined ? {} : { cutoffDistance: operation.cutoff_distance }),
});
