# This file is auto-generated by scripts/generate_stage_scene_ops.py
# Do not edit manually - run 'npm run generate-stage-scene-ops' to update

def generated_camera_manifest_fields(camera: object) -> dict:
    return {"focusDistance": float(getattr(getattr(camera, "dof"), "focus_distance"))}

def generated_light_manifest_fields(light: object) -> dict:
    return {"cutoffDistance": float(getattr(light, "cutoff_distance"))}
