"""Cross-language SceneManifestV2 revision parity (Architecture §6).

The committed fixture is generated by real Blender extraction through
tests/fixtures/generate_scene_manifest_v2_parity.py and shared verbatim with
packages/director-core/test/fixtures/scene-manifest-v2-parity.json. This test
proves Python reproduces the extracted sceneHash and revisionId; the
director-core parity test proves TypeScript reproduces the same values.
"""

import json
import os
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from cclay.scene_manifest import finalize_scene_manifest

FIXTURE_PATH = os.path.join(
    os.path.dirname(__file__),
    "..",
    "..",
    "packages",
    "director-core",
    "test",
    "fixtures",
    "scene-manifest-v2-parity.json",
)


class SceneManifestParityTest(unittest.TestCase):
    def test_architecture_section_6_and_snapshot_v2_section_2_6_reproduce_the_committed_v2_hash(self):
        with open(FIXTURE_PATH, encoding="utf-8") as handle:
            fixture = json.load(handle)
        self.assertEqual(fixture["scene"]["name"], "Blender Generated V2 Parity")
        self.assertEqual(
            {animation["target"] for animation in fixture["cameraAnimations"]},
            {"object", "cameraData"},
        )
        keyframes = [
            keyframe
            for animation in fixture["cameraAnimations"]
            for fcurve in animation["fcurves"]
            for keyframe in fcurve["keyframes"]
        ]
        self.assertTrue(keyframes)
        self.assertTrue(
            all(
                keyframe["handleLeftType"] == "AUTO_CLAMPED"
                and keyframe["handleRightType"] == "AUTO_CLAMPED"
                for keyframe in keyframes
            )
        )
        self.assertTrue(fixture["selectedEntityIds"])
        without_hashes = {k: v for k, v in fixture.items() if k not in ("sceneHash", "revisionId")}
        rebuilt = finalize_scene_manifest(without_hashes)
        self.assertEqual(rebuilt["sceneHash"], fixture["sceneHash"])
        self.assertEqual(rebuilt["revisionId"], fixture["revisionId"])


if __name__ == "__main__":
    unittest.main()
