# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: CozyClay contributors
"""Generate each adjacent captured-pose interval independently and assemble one clip.

This is the interval counterpart to cclay_constrained_generate.py. It never
splices arbitrary caller-supplied arrays: every segment is generated by ARDY
from a validated slice of one base archive, adjacent segments share the same
captured endpoint pose, and this script validates schema, fps, frame count,
finite values, duplicate-boundary continuity, and the final assembled clip
before publishing one npz.
"""

import argparse
import json
import math
import os
import subprocess
import sys
import tempfile

FRAME_KEYS = (
    "local_rot_mats",
    "global_rot_mats",
    "posed_joints",
    "root_positions",
    "smooth_root_pos",
    "foot_contacts",
    "global_root_heading",
)


def parse_args():
    parser = argparse.ArgumentParser(description="Interval-wise ARDY in-between assembly")
    parser.add_argument("--prompt", required=True)
    parser.add_argument("--base", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--pose-from", action="append", nargs=3, default=[])
    parser.add_argument("--seed", type=int, default=None)
    return parser.parse_args()


def output_path(stem):
    path = stem if stem.endswith(".npz") else f"{stem}.npz"
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    return path


def load_base(path):
    import numpy as np

    with np.load(path) as data:
        missing = [key for key in FRAME_KEYS if key not in data]
        if missing:
            raise ValueError(f"base archive is missing frame arrays: {missing}")
        arrays = {key: np.asarray(data[key]) for key in FRAME_KEYS}
        if "fps" not in data:
            raise ValueError("base archive is missing fps")
        fps = int(np.asarray(data["fps"]).item())
    frames = int(arrays["local_rot_mats"].shape[0])
    if fps <= 0 or frames < 2:
        raise ValueError(f"base archive has invalid frames/fps: {frames}/{fps}")
    for key, value in arrays.items():
        if value.shape[0] != frames:
            raise ValueError(f"base array {key} has {value.shape[0]} frames, expected {frames}")
    return arrays, frames, fps


def parse_poses(raw, frame_count):
    poses = []
    seen = set()
    for source, raw_source_frame, raw_destination_frame in raw:
        source_frame = int(raw_source_frame)
        destination_frame = int(raw_destination_frame)
        if not os.path.isfile(source):
            raise ValueError(f"pose source not found: {source}")
        if source_frame < 0 or not 0 <= destination_frame < frame_count:
            raise ValueError(f"pose frame is outside its source/base: {source_frame}/{destination_frame}")
        if destination_frame in seen:
            raise ValueError(f"duplicate captured pose at frame {destination_frame}")
        seen.add(destination_frame)
        poses.append((destination_frame, source, source_frame))
    poses.sort()
    if len(poses) < 2:
        raise ValueError("interval assembly needs at least two captured poses")
    if poses[0][0] != 0 or poses[-1][0] != frame_count - 1:
        raise ValueError(
            f"captured poses must include clip endpoints 0 and {frame_count - 1}, "
            f"got {poses[0][0]} and {poses[-1][0]}"
        )
    return poses


def save_base_slice(path, arrays, start, end, fps, prompt):
    import numpy as np

    sliced = {key: value[start : end + 1] for key, value in arrays.items()}
    sliced["fps"] = np.asarray(fps)
    sliced["text"] = np.asarray(prompt)
    np.savez(path, **sliced)


def load_segment(path, expected_frames, fps):
    import numpy as np

    with np.load(path) as data:
        missing = [key for key in FRAME_KEYS if key not in data]
        if missing:
            raise ValueError(f"generated segment is missing frame arrays: {missing}")
        if int(np.asarray(data["fps"]).item()) != fps:
            raise ValueError("generated segment fps differs from the base clip")
        arrays = {key: np.asarray(data[key]) for key in FRAME_KEYS}
    for key, value in arrays.items():
        if value.shape[0] != expected_frames:
            raise ValueError(
                f"generated segment array {key} has {value.shape[0]} frames, expected {expected_frames}"
            )
        if value.dtype.kind in "fc" and not np.isfinite(value).all():
            raise ValueError(f"generated segment array {key} contains non-finite values")
    return arrays


def continuity(posed_joints):
    import numpy as np

    jumps = np.linalg.norm(posed_joints[1:] - posed_joints[:-1], axis=-1).max(axis=-1)
    return {
        "mean_jump_m": float(jumps.mean()),
        "max_jump_m": float(jumps.max()),
        "max_jump_frame": int(jumps.argmax()) + 1,
    }


def main():
    import numpy as np

    args = parse_args()
    base, frame_count, fps = load_base(args.base)
    poses = parse_poses(args.pose_from, frame_count)
    constrained_script = os.path.join(os.path.dirname(__file__), "cclay_constrained_generate.py")
    assembled = {key: [] for key in FRAME_KEYS}
    intervals = []
    with tempfile.TemporaryDirectory(prefix="cclay-inbetween-") as temporary:
        previous_endpoint = None
        for index, (left, right) in enumerate(zip(poses, poses[1:])):
            start, left_source, left_source_frame = left
            end, right_source, right_source_frame = right
            segment_frames = end - start + 1
            if segment_frames < 3:
                raise ValueError(f"interval {start}..{end} has fewer than three frames")
            base_path = os.path.join(temporary, f"base-{index}.npz")
            segment_stem = os.path.join(temporary, f"segment-{index}")
            save_base_slice(base_path, base, start, end, fps, args.prompt)
            command = [
                sys.executable,
                constrained_script,
                "--prompt",
                args.prompt,
                "--duration",
                str(segment_frames / fps),
                "--base",
                base_path,
                "--pose-from",
                left_source,
                str(left_source_frame),
                "0",
                "--pose-from",
                right_source,
                str(right_source_frame),
                str(segment_frames - 1),
                "--output",
                segment_stem,
            ]
            if args.seed is not None:
                command.extend(["--seed", str(args.seed + index)])
            completed = subprocess.run(command, check=True, text=True, capture_output=True)
            if completed.stderr:
                print(completed.stderr, file=sys.stderr, end="")
            segment = load_segment(f"{segment_stem}.npz", segment_frames, fps)
            boundary_jump = 0.0
            if previous_endpoint is not None:
                boundary_jump = float(
                    np.linalg.norm(previous_endpoint - segment["posed_joints"][0], axis=-1).max()
                )
            previous_endpoint = segment["posed_joints"][-1]
            for key in FRAME_KEYS:
                assembled[key].append(segment[key] if index == 0 else segment[key][1:])
            intervals.append(
                {
                    "start_frame": start,
                    "end_frame": end,
                    "frames": segment_frames,
                    "boundary_jump_m": boundary_jump,
                }
            )
    output = {key: np.concatenate(parts, axis=0) for key, parts in assembled.items()}
    if output["local_rot_mats"].shape[0] != frame_count:
        raise ValueError(
            f"assembled clip has {output['local_rot_mats'].shape[0]} frames, expected {frame_count}"
        )
    for key, value in output.items():
        if value.dtype.kind in "fc" and not np.isfinite(value).all():
            raise ValueError(f"assembled array {key} contains non-finite values")
    destination = output_path(args.output)
    np.savez(destination, **output, fps=np.asarray(fps), text=np.asarray(args.prompt))
    metrics = continuity(output["posed_joints"])
    print(
        json.dumps(
            {
                "frames": frame_count,
                "fps": fps,
                "continuity": metrics,
                "intervals": intervals,
                "max_boundary_jump_m": max(interval["boundary_jump_m"] for interval in intervals),
            }
        )
    )


if __name__ == "__main__":
    main()
