#!/usr/bin/env python3
"""Generate direct single-property StageScene RNA operation support."""
from __future__ import annotations

import ast
import hashlib
import json
import math
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "packages/blender-protocol/src/op-registry.json"
STAGE_SCENE = ROOT / "blender-addon/cclay/stage_scene.py"
HEADER_TS = "// This file is auto-generated by scripts/generate_stage_scene_ops.py\n// Do not edit manually - run 'npm run generate-stage-scene-ops' to update\n\n"
HEADER_PY = "# This file is auto-generated by scripts/generate_stage_scene_ops.py\n# Do not edit manually - run 'npm run generate-stage-scene-ops' to update\n\n"
IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
TARGET_TYPES = {"CAMERA": "Camera", "LIGHT": "Light"}
# (TypeBox constructor, TS type name, injected Python validator, Python cast)
# The validator slot must name the function the executor is given, not the
# builtin: emitting float(value, path, minimum=..., maximum=...) type-errors on
# every call, which silently disabled all generated bounds checking.
VALUE_TYPES = {"number": ("Type.Number", "number", "number", "float")}
MANIFEST_PATHS = {
    "cameras[].focusDistance": ("Camera", "Camera", "focusDistance"),
    "lights[].cutoffDistance": ("Light", "Light", "cutoffDistance"),
}

# Identifier-shaped segments are not enough. `data.animation_data.action.name`
# is all-identifiers but traverses out of the entity's own datablock into a
# shared Action, which _require_exclusive_datablocks cannot protect because that
# guard is applied to the scene object. Generated code writes to a live scene,
# so the reachable write targets are an explicit reviewed allowlist per target
# type rather than anything the segment shape happens to permit.
ALLOWED_RNA_PATHS = {
    "CAMERA": {"data.dof.focus_distance", "data.lens", "data.clip_start", "data.clip_end"},
    "LIGHT": {"data.cutoff_distance", "data.energy", "data.shadow_soft_size"},
}


def row_label(index: int, row: object) -> str:
    return f"registry row {index}" + (f" ({row.get('op')!r})" if isinstance(row, dict) else "")


def handwritten_operation_names() -> set[str]:
    tree = ast.parse(STAGE_SCENE.read_text(encoding="utf-8"), filename=str(STAGE_SCENE))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(isinstance(target, ast.Name) and target.id == "_OPERATION_KEYS" for target in node.targets):
            value = ast.literal_eval(node.value)
            return set(value)
    raise ValueError("could not read hand-written _OPERATION_KEYS from stage_scene.py")


def validate_rows(rows: object) -> list[dict]:
    if not isinstance(rows, list):
        raise ValueError("registry must be an array")
    handwritten = handwritten_operation_names()
    seen: set[str] = set()
    validated = []
    for index, row in enumerate(rows):
        label = row_label(index, row)
        if not isinstance(row, dict):
            raise ValueError(f"{label}: row must be an object")
        op = row.get("op")
        if not isinstance(op, str) or not IDENTIFIER.fullmatch(op):
            raise ValueError(f"{label}: op must be a plain identifier")
        if op in seen:
            raise ValueError(f"{label}: duplicate op {op!r}")
        if op in handwritten:
            raise ValueError(f"{label}: op {op!r} collides with hand-written _OPERATION_KEYS")
        seen.add(op)
        for field in ("wireField",):
            value = row.get(field)
            if not isinstance(value, str) or not IDENTIFIER.fullmatch(value):
                raise ValueError(f"{label}: {field} must be a plain identifier")
        resolver = row.get("targetResolver")
        if resolver != "entity":
            raise ValueError(f"{label}: targetResolver must be 'entity'")
        target_type = row.get("targetType")
        if target_type not in TARGET_TYPES:
            raise ValueError(f"{label}: targetType {target_type!r} is not a recognized Blender target type")
        value_type = row.get("valueType")
        if value_type not in VALUE_TYPES:
            raise ValueError(f"{label}: valueType {value_type!r} is not supported")
        rna_path = row.get("rnaPath")
        if not isinstance(rna_path, str):
            raise ValueError(f"{label}: rnaPath must be a dotted path")
        segments = rna_path.split(".")
        if not segments or any(not IDENTIFIER.fullmatch(segment) or segment.startswith("__") or segment.endswith("__") for segment in segments):
            raise ValueError(f"{label}: rnaPath contains a non-identifier, dunder, or traversal segment")
        if rna_path not in ALLOWED_RNA_PATHS.get(target_type, frozenset()):
            raise ValueError(
                f"{label}: rnaPath {rna_path!r} is not an allowed {target_type} write target; "
                f"paths must stay inside the entity's own datablock and be added to ALLOWED_RNA_PATHS after review"
            )
        bounds = row.get("bounds")
        if not isinstance(bounds, dict) or not isinstance(bounds.get("min"), (int, float)) or isinstance(bounds.get("min"), bool) or not isinstance(bounds.get("max"), (int, float)) or isinstance(bounds.get("max"), bool):
            raise ValueError(f"{label}: bounds must contain numeric min and max")
        minimum, maximum = bounds["min"], bounds["max"]
        if not math.isfinite(minimum) or not math.isfinite(maximum):
            raise ValueError(f"{label}: bounds min and max must be finite")
        if minimum > maximum:
            raise ValueError(f"{label}: bounds min must not exceed max")
        manifest_path = row.get("manifestFieldPath")
        if manifest_path not in MANIFEST_PATHS or MANIFEST_PATHS[manifest_path][0] != TARGET_TYPES[target_type]:
            raise ValueError(f"{label}: manifestFieldPath {manifest_path!r} does not match the {target_type} manifest shape")
        stage_scene_operation = row.get("stageSceneOperation", True)
        if not isinstance(stage_scene_operation, bool):
            raise ValueError(f"{label}: stageSceneOperation must be a boolean")
        validated.append(row)
    return validated
def manifest_value_expression(row: dict, target_name: str) -> str:
    expression = target_name.lower()
    for segment in row["rnaPath"].split(".")[1:]:
        expression = f"getattr({expression}, {json.dumps(segment)})"
    return expression




def ts_number(value: float) -> str:
    return json.dumps(value, allow_nan=False)


def outputs(rows: list[dict]) -> dict[str, str]:
    schemas = []
    projections = []
    keys = []
    validators = []
    executors = []
    manifest_groups: dict[str, list[dict]] = {}
    for row in rows:
        op, field = row["op"], row["wireField"]
        minimum, maximum = row["bounds"]["min"], row["bounds"]["max"]
        _, target_name, _manifest_field = MANIFEST_PATHS[row["manifestFieldPath"]]
        manifest_groups.setdefault(target_name, []).append(row)
        if row.get("stageSceneOperation", True) is False:
            continue
        schema_index = len(schemas)
        schemas.append(f'''const GeneratedStageSceneOperationSchema{schema_index} = Type.Object(\n\t{{\n\t\top: Type.Literal({json.dumps(op)}),\n\t\tentity_id: Type.String({{ pattern: "^[0-9a-f]{{8}}-[0-9a-f]{{4}}-4[0-9a-f]{{3}}-[89ab][0-9a-f]{{3}}-[0-9a-f]{{12}}$" }}),\n\t\t{field}: {VALUE_TYPES[row["valueType"]][0]}({{ minimum: {ts_number(minimum)}, maximum: {ts_number(maximum)} }}),\n\t}},\n\t{{ additionalProperties: false }},\n);''')
        keys.append(f'    {json.dumps(op)}: {{"op", "entity_id", {json.dumps(field)}}},')
        validators.append(f'''    if operation["op"] == {json.dumps(op)}:\n        {VALUE_TYPES[row["valueType"]][2]}(operation[{json.dumps(field)}], f"operations[{{index}}].{field}", minimum={float(minimum)!r}, maximum={float(maximum)!r})\n        return''')
        path = row["rnaPath"].split(".")
        parent = "scene_object"
        for segment in path[:-1]:
            parent = f"getattr({parent}, {json.dumps(segment)})"
        target_expr = parent
        executors.append(f'''    if operation["op"] == {json.dumps(op)}:\n        scene_object = require_owned_entity(operation["entity_id"], project_id)\n        if not isinstance(scene_object.data, bpy.types.{TARGET_TYPES[row["targetType"]]}):\n            raise invalid_entity_type(\n                f"entity {{operation['entity_id']}} must be a {row['targetType']}"\n            )\n        require_exclusive_datablocks(scene_object)\n        transaction.capture_object(scene_object)\n        setattr({target_expr}, {json.dumps(path[-1])}, operation[{json.dumps(field)}])\n        return''')
    for target_name, group in manifest_groups.items():
        params = ", ".join(f'{row["wireField"]}?: {VALUE_TYPES[row["valueType"]][1]}' for row in group)
        body = "\n".join(
            f'\t...(operation.{row["wireField"]} === undefined ? {{}} : {{ {MANIFEST_PATHS[row["manifestFieldPath"]][2]}: operation.{row["wireField"]} }}),'
            for row in group
        )
        projections.append(
            f"export const generated{target_name}ManifestFields = (operation: {{ {params} }}) => ({{\n{body}\n}});"
        )
    typebox_import = 'import { Type } from "typebox";\n\n' if schemas else ""
    schema_exports = (
        "export const GeneratedStageSceneOperationSchemas = [\n"
        + "\n".join(
            f"\tGeneratedStageSceneOperationSchema{index},"
            for index in range(len(schemas))
        )
        + "\n] as const;"
        if schemas
        else "export const GeneratedStageSceneOperationSchemas = [] as const;"
    )
    ts = (
        HEADER_TS
        + typebox_import
        + ("\n\n".join(schemas) + "\n\n" if schemas else "")
        + schema_exports
        + "\n\nexport const GeneratedStageSceneRequestOperationSchemas = GeneratedStageSceneOperationSchemas;\n\n"
        + "\n\n".join(projections)
        + "\n"
    )
    py = HEADER_PY + "GENERATED_OPERATION_KEYS = {\n" + "\n".join(keys) + "\n}\n\n\ndef validate_generated_operation(operation: dict, index: int, number) -> None:\n" + ("\n".join(validators) if validators else "    return") + "\n\n\ndef execute_generated_operation(\n    operation: dict, transaction, project_id: str, require_owned_entity,\n    require_exclusive_datablocks, bpy, invalid_entity_type,\n) -> None:\n" + ("\n".join(executors) if executors else "    return") + "\n"
    manifest_ts_parts = ['import { Type } from "typebox";']
    manifest_py_parts = []
    for target_name, group in manifest_groups.items():
        export = f"Generated{target_name}ManifestFields"
        manifest_ts_parts.append("export const " + export + " = {\n" + "\n".join(f'\t{MANIFEST_PATHS[row["manifestFieldPath"]][2]}: Type.Optional({VALUE_TYPES[row["valueType"]][0]}({{ minimum: {ts_number(row["bounds"]["min"])}, maximum: {ts_number(row["bounds"]["max"])} }})),' for row in group) + "\n};")
        manifest_py_parts.append(f"def generated_{target_name.lower()}_manifest_fields({target_name.lower()}: object) -> dict:\n    return {{" + ", ".join(f'{json.dumps(MANIFEST_PATHS[row["manifestFieldPath"]][2])}: float({manifest_value_expression(row, target_name)})' for row in group) + "}")
    manifest_ts = HEADER_TS + "\n\n".join(manifest_ts_parts) + "\n"
    manifest_py = HEADER_PY + "\n\n".join(manifest_py_parts) + "\n"
    fixture_rows = []
    for row in rows:
        field = row["wireField"]
        value = max(row["bounds"]["min"], min(row["bounds"]["max"], 12.5))
        operation = {"op": row["op"], "entity_id": "123e4567-e89b-42d3-a456-426614174000", field: value}
        manifest_field = MANIFEST_PATHS[row["manifestFieldPath"]][2]
        canonical = json.dumps({manifest_field: value}, ensure_ascii=False, separators=(",", ":"))
        fixture_rows.append({"operation": operation, "stageSceneOperation": row.get("stageSceneOperation", True), "canonicalFields": canonical, "sha256": hashlib.sha256(canonical.encode()).hexdigest()})
    fixture = json.dumps(fixture_rows, indent=2) + "\n"
    return {
        "packages/blender-protocol/src/stage-scene-ops.generated.ts": ts,
        "blender-addon/cclay/stage_scene_ops_generated.py": py,
        "packages/blender-protocol/src/manifest-fields.generated.ts": manifest_ts,
        "blender-addon/cclay/manifest_fields_generated.py": manifest_py,
        "packages/blender-protocol/test/fixtures/canonical-fields.generated.json": fixture,
    }


def main() -> int:
    rows = validate_rows(json.loads(REGISTRY.read_text(encoding="utf-8")))
    rendered = outputs(rows)
    check = "--check" in sys.argv[1:]
    dirty = []
    for name, text in rendered.items():
        path = ROOT / name
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                dirty.append(name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    if dirty:
        print("generated files differ: " + ", ".join(dirty), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
